export const data = [
  {
    CustomerName: 'Bryan',
    StreetAddress: '31 Mountain AV',
    Phone: '9086472130',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: 'Stive',
    StreetAddress: '116 Liberty Corner Far Hill',
    Phone: '9085813788',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: 'Mrs. Ruderman',
    StreetAddress: '23 Hadley CT',
    Phone: '2012644252',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '99 Sunset LN ',
    Phone: '',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: 'Stephanie',
    StreetAddress: '116 Meeker RD',
    Phone: '9088480261',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '95 Blackburn RD',
    Phone: '9082080787',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: 'Lucille Boudreau',
    StreetAddress: '33 Pheasent Run DR',
    Phone: '',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: 'Jessica',
    StreetAddress: '14 Lindsley RD',
    Phone: '2017078004',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '374 South Maple AV',
    Phone: '9082967658',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: 'Sara',
    StreetAddress: '140 Lees Hill RD',
    Phone: '9739458916',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: 'Joe Calise',
    StreetAddress: '40 Sunybrook RD',
    Phone: '2672504405',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: 'Bianca',
    StreetAddress: '10 Fieldstone DR',
    Phone: '9085001296',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '21 Canter DR',
    Phone: '',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '161 Culberson RD',
    Phone: '',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: 'Tracy Pester',
    StreetAddress: '34 Fox Hunt RD',
    Phone: '9737235721',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    Zipcode: '07920',
    City: 'Basking_Ridge',
    State: 'NJ',
  },
  {
    CustomerName: 'Mr. Susman',
    StreetAddress: '515 Flower RD',
    Phone: '9087819411',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'Bedminster',
    Zipcode: '07921',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '1531 Larger Cross RD',
    Phone: '9082563632',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'Bedminster',
    Zipcode: '07921',
    State: 'NJ',
  },
  {
    CustomerName: 'James Cheson',
    StreetAddress: '2360 Larger Cross Rd.',
    Phone: '9082565570',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'Bedminster',
    Zipcode: '07921',
    State: 'NJ',
  },
  {
    CustomerName: 'Rob Samenth',
    StreetAddress: '2012 Lamington RD.',
    Phone: '9732145680',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'Bedminster',
    Zipcode: '07921',
    State: 'NJ',
  },
  {
    CustomerName: 'Giselle',
    StreetAddress: '243 Sutton DR',
    Phone: '9083375723',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '57 Kline PL',
    Phone: '9084187249',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'Willy Solis',
    StreetAddress: '1011 Mountain AV ',
    Phone: '',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '89 Sutton DR',
    Phone: '9737697030',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'Karin Ruhkala',
    StreetAddress: '49 Kline PL',
    Phone: '9178485339',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'Michael Vapenik',
    StreetAddress: '96 Baker AV',
    Phone: '6467340075',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'Mike Cranston',
    StreetAddress: '22 Holly Glen LN',
    Phone: '2014819901',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '6 Barnstable CT',
    Phone: '2013104348',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'Jim Rubiano',
    StreetAddress: '51 Kline BLVD ',
    Phone: '9085783344',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'Diane Kamerer',
    StreetAddress: '14 Horseshoe RD',
    Phone: '7324292721',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'Katheleen Hager',
    StreetAddress: '14 Deer Path LN',
    Phone: '9083349938',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '23 Whitney DR',
    Phone: '9176178656',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'John Kempf',
    StreetAddress: '8 Holly Mews ',
    Phone: '9084158762',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'Lorraine Dias',
    StreetAddress: '4 Tree Top',
    Phone: '8624521767',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '11 Debbie PL',
    Phone: '9085079271',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '111 Orchard LN',
    Phone: '2013909884',
    LastServiceDate: '',
    Payment: '',
    Email: '',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '20 Rutger AV',
    Phone: '',
    LastServiceDate: '',
    Payment: '',
    Email: '',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '211 Sutton DR',
    Phone: '9087680332',
    LastServiceDate: '',
    Payment: '',
    Email: '',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'Hornos',
    StreetAddress: '63 Bristol CT',
    Phone: '9088128064',
    LastServiceDate: '',
    Payment: '',
    Email: '',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'Dan Bartiromo',
    StreetAddress: '110 Washington ST',
    Phone: '9087392459',
    LastServiceDate: '',
    Payment: '',
    Email: '',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '212 Springfield AV',
    Phone: '',
    LastServiceDate: '',
    Payment: '',
    Email: '',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '149 Cornell AV',
    Phone: '2012137720',
    LastServiceDate: '',
    Payment: '',
    Email: '',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'Cindy Dineu',
    StreetAddress: '70 Exeter DR',
    Phone: '9736879849',
    LastServiceDate: '',
    Payment: '',
    Email: '',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '5 River Bend',
    Phone: '',
    LastServiceDate: '',
    Payment: '',
    Email: '',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '211 Sutton DR',
    Phone: '(908)7680332',
    LastServiceDate: '',
    Payment: '',
    Email: '',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '142 Lawrence Dr',
    Phone: '(908)5536365',
    LastServiceDate: '',
    Payment: '',
    Email: '',
    Notes: '',
    City: 'berkeley_heights',
    Zipcode: '07922',
    State: 'NJ',
  },
  {
    CustomerName: 'Claudio Zamarra',
    StreetAddress: '28 Anderson Hill',
    Phone: '2014631349',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'bernardsville',
    Zipcode: '07924',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: ' 49 Shadobrook CT',
    Phone: '9082956991',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'bernardsville',
    Zipcode: '07924',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '29 Windwood RD',
    Phone: '2036057373',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'bernardsville',
    Zipcode: '07924',
    State: 'NJ',
  },
  {
    CustomerName: 'Jason Bogdan',
    StreetAddress: '18 Dobbs ST',
    Phone: '9086729020',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'bernardsville',
    Zipcode: '07924',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: 'Mendhan',
    Phone: '',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'bernardsville',
    Zipcode: '07924',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '6 Laurelwood Dr',
    Phone: '2013204620',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'bernardsville',
    Zipcode: '07924',
    State: 'NJ',
  },
  {
    CustomerName: 'John',
    StreetAddress: '21 Harvey DR',
    Phone: '6164509498',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'bernardsville',
    Zipcode: '07924',
    State: 'NJ',
  },
  {
    CustomerName: '',
    StreetAddress: '27 Mt. Harmony Road',
    Phone: '(908) 432 9081',
    LastServiceDate: '',
    Payment: '',
    Email: 'N/A',
    Notes: '',
    City: 'bernardsville',
    Zipcode: '07924',
    State: 'NJ',
  },
]
